
[project]
name = "bitflow-stableswap"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.sip-010-trait-ft-standard-v-1-1]
path = "contracts/sip-010-trait-ft-standard-v-1-1.clar"
clarity_version = 2
epoch = "2.1"

[contracts.stableswap-pool-trait-v-1-1]
path = "contracts/stableswap-pool-trait-v-1-1.clar"
clarity_version = 2
epoch = "2.1"

[contracts.stableswap-core-v-1-1]
path = "contracts/stableswap-core-v-1-1.clar"
clarity_version = 2
epoch = "2.1"

[contracts.stableswap-pool-stx-ststx-v-1-1]
path = "contracts/stableswap-pool-stx-ststx-v-1-1.clar"
clarity_version = 2
epoch = "2.1"

[contracts.token-stx-v-1-1]
path = "contracts/token-stx-v-1-1.clar"
clarity_version = 2
epoch = "2.1"

[contracts.token-ststx]
path = "contracts/external/token-ststx.clar"
clarity_version = 2
epoch = "2.1"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
